const moreSongs = [
  {
    title: "Bronski Beat - Smalltown Boy",
    sheet: "Am - G - Dm - F capo en 3er traste",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "RHCP - Snow",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Santo es el fingerstyle",
    sheet: "Em - D - C - Bm",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Star wars Song",
    sheet: "Em - C - G - D",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Tio José",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Lenny Kravitz - Are you gonna go my way",
    sheet: "14 - 12",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Aerosmith - Dream on (acordes)",
    sheet: "Em - G - D - A",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Tokyo Hotel - Monsoon",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Lady Gaga Paparazzi estribillo",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "La cumparsita Intro",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Foster the people - Pumped up Kicks",
    sheet: "Em - G - D - A",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "La Vestido celeste",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Hoy te vi de la mano con el",
    sheet: "Em - C - G - D",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Led Zeppelin - Stairway to Heaven",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "ACDC - TNT",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Los piojos - Bicho de ciudad",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Maroon 5 - She will be love",
    sheet: "Capo 3. C - G - Am - F",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Ozuna - Pajaritos en el Aire (acordes)",
    sheet: "Fm - Bm - E",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Twenty One Pilots - Heathens",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Granadina",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "The Police - Message in a Bottle",
    sheet: "C#2 - A2 - B2 - F#2",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Metallica - Nothing Else Matters",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "La T y la M - Pa la seleccion",
    sheet: "Bm - A2 - Em",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Adios Nonino Intro",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Ling Tosite Segure - Unravel",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "HSM - Breaking Free",
    sheet: "Am - D - C - G",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Lil nas X - Old town road",
    sheet: "Em - G - D - A",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "BTS - sWEET nIGHT",
    sheet: "Capo 3 C - G - Am - F",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "BTS - Spring Day",
    sheet: "Capo 3 C - G - Am - F",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
  {
    title: "Kina - Get You The Moon",
    sheet: "F - Am - G capo en 4to traste",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },

  {
    title: "One Piece - We Are Intro",
    sheet: "",
    author: "",
    image: "",
    type: "",
    level: 0,
    difficulty: 0,
  },
];
